SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
GAME_TITLE = "astro-vex"

PLAYER_RADIUS = 20
LINE_WIDTH = 2

PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
PLAYER_STARTING_LIVES = 3
PLAYER_RESPAWN_INVULNERABLE_SECONDS = 2.0
PLAYER_RESPAWN_COUNTDOWN_SECONDS = 3.0

PLAYER_ACCELERATION = 500
PLAYER_DRAG = 0.9

WEAPON_SINGLE_COOLDOWN_SECONDS = 0.3
WEAPON_SPREAD_COOLDOWN_SECONDS = 0.45
WEAPON_RAPID_COOLDOWN_SECONDS = 0.12
WEAPON_SPREAD_ANGLE_DEGREES = 18

SHOT_RADIUS = 5

PLAYER_BOMB_COOLDOWN_SECONDS = 1.0
BOMB_STARTING_COUNT = 3
BOMB_RADIUS = 6
BOMB_FUSE_SECONDS = 1.2
BOMB_BLAST_RADIUS = 180

POWERUP_RADIUS = 10
POWERUP_SPAWN_SECONDS = 8.0
SHIELD_DURATION_SECONDS = 6.0
SPEED_BOOST_DURATION_SECONDS = 6.0
SPEED_BOOST_MULTIPLIER = 1.7

SOUND_DEFAULT_VOLUME = 0.5

EXPLOSION_DURATION_SECONDS = 0.25
EXPLOSION_GROWTH_SCALE = 1.8

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
