SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
GAME_TITLE = "astro-vex"

PLAYER_RADIUS = 20
LINE_WIDTH = 2

PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
PLAYER_STARTING_LIVES = 3
PLAYER_RESPAWN_INVULNERABLE_SECONDS = 2.0
PLAYER_RESPAWN_COUNTDOWN_SECONDS = 3.0

PLAYER_ACCELERATION = 500
PLAYER_DRAG = 0.9

WEAPON_SINGLE_COOLDOWN_SECONDS = 0.3
WEAPON_SPREAD_COOLDOWN_SECONDS = 0.45
WEAPON_RAPID_COOLDOWN_SECONDS = 0.12
WEAPON_SPREAD_ANGLE_DEGREES = 18

SHOT_RADIUS = 5

PLAYER_BOMB_COOLDOWN_SECONDS = 1.0
BOMB_STARTING_COUNT = 3
BOMB_RADIUS = 6
BOMB_FUSE_SECONDS = 1.2
BOMB_BLAST_RADIUS = 180

POWERUP_RADIUS = 10
POWERUP_SPAWN_SECONDS = 8.0
SHIELD_DURATION_SECONDS = 6.0
SPEED_BOOST_DURATION_SECONDS = 6.0
SPEED_BOOST_MULTIPLIER = 1.7

SOUND_DEFAULT_VOLUME = 0.5

MULTIPLAYER_SERVER_HOST = "127.0.0.1"
MULTIPLAYER_SERVER_PORT = 8765
MULTIPLAYER_ROOM_SIZE = 4
NETWORK_SEND_INTERVAL_SECONDS = 0.05

WAVE_DURATION_SECONDS = 20.0

SCREEN_SHAKE_EXPLOSION_INTENSITY = 6
SCREEN_SHAKE_BOMB_INTENSITY = 10
SCREEN_SHAKE_BOSS_DEATH_INTENSITY = 16
SCREEN_SHAKE_BASE_DURATION_SECONDS = 0.18

PARALLAX_LAYER_SPEEDS = (16, 32, 56)
PARALLAX_LAYER_COUNTS = (80, 50, 35)

DRONE_RADIUS = 10
DRONE_BASE_HEALTH = 4
DRONE_BASE_RANGE = 260
DRONE_BASE_COOLDOWN_SECONDS = 0.5
DRONE_SHOT_SPEED = 460
DRONE_MAX_LEVEL = 4

BOSS_SPAWN_CHANCE = 0.08
BOSS_RADIUS_MULTIPLIER = 4

EXPLOSION_DURATION_SECONDS = 0.25
EXPLOSION_GROWTH_SCALE = 1.8

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
